### PR TITLE
Our Team Page

### PR DESCRIPTION
**Pull request by vampnik**
I have added the csss in main.css and have a dedicated file named Our Team.html which contains the code for the Our Team page.

### CODE REVIEW

**Comment by pulkithanda** [comment]
@vampnik You have to add the team section in the main home.html file and run and try if you are able to see it.

**Comment by vampnik** [comment]
@pulkithanda Ok will update that too. Is there any more changes ??

**Comment by pulkithanda** [comment]
Nah @vampnik Did you do these changes and were able to see team section in the home page after logging in and before logging in at both times ? Do tell me so that I can check

**Comment by vampnik** [comment]
I have added it to the home page and it's working.

**Comment by pulkithanda** [comment]
Uhh @vampnik Hey contact me through discord ? There's a major bug in the code.

**Comment by vampnik** [comment]
Drop on your discord username and hash will add you. @pulkithanda

**Comment by pulkithanda** [comment]
Hey @vampnik It's Alphabet# 0352 Sorry for replying late, exams!
Your code is somewhat messing up with the pages all the colours have turned well disco lights and no team page 😂

**Comment by vampnik** [comment]
@pulkithanda it's ok :)
I have sent you the request please check it out

**Comment by pulkithanda** [comment]
image
No team page its just merging colours into other sections ?

**Comment by pulkithanda** [comment]
Hey there @vampnik You must have worked hard and since its the last day for hacktoberfest well, A gift
(btw if you could follow me on Github and star the repo it would help me)

**Pull request closed without merging**
