### PR TITLE
Added a new section Missions Space and renamed procedures - Missions

### PR DESCRIPTION
**Pull request by GeorgeET15**
I have made the changes sir. please accept my PR :)

New Home

### CODE REVIEW

**Comment by pulkithanda** [comment]
@GeorgeET15 in the missions section you need to add missions for the space section like NASA or any space website has. Also incorporate the procedures in that only no need for the "missions space" section. Please do these changes. For examples:
https://codepen.io/bramus/pen/PobmGme https://codepen.io/royemosby/pen/rXjEEm https://codepen.io/HenrikFricke/pen/eYByWPw Something like these in card forms mission 1 mission 2 under a mission section.

**Comment by GeorgeET15** [comment]
In NASA's website there is a drop-down list when click missions so you want one like tha
NASA
t.

**Comment by pulkithanda** [comment]
@GeorgeET15 I just want missions in card form in the missions section like I sent you above. You just have to see the format from a website like NASA, you have the card design just edit it, create 4 5 missions and you're good to go.

**Comment by pulkithanda** [comment]
Hey there @GeorgeET15 You must have worked hard and since its the last day for hacktoberfest well, A gift
(btw if you could follow me on Github and star the repo it would help me)

**Comment by GeorgeET15** [comment]
Thanks 😊.

**Comment by pulkithanda** [comment]
btw @GeorgeET15 Can you follow me as a help to me? (⌐■_■)

**Pull request closed without merging**
