### PR TITLE
added search button

### PR DESCRIPTION
**Pull request by JanviRaina**

### CODE REVIEW

**Comment by JanviRaina** [comment]
Hey can you review my PR.

**Comment by pulkithanda** [comment]
Hey @JanviRaina, Sorry but give sometime please (exams) will definitely view it tomorrow

**Comment by pulkithanda** [comment]
Hey @JanviRaina  please resolve the merge conflicts

**Comment by JanviRaina** [comment]
> Hey @JanviRaina, Sorry but give sometime please (exams) will definitely view it tomorrow

No problem at all.

**Comment by pulkithanda** [comment]
Hey, @JanviRaina I cloned your repository to see the changes but didn't find any !? Can you check once if your forked repository has all the changes?

**Comment by JanviRaina** [comment]
> Hey, @JanviRaina I cloned your repository to see the changes but didn't find any !? Can you check once if your forked repository has all the changes?

I can see the changes in 'janvir' branch

**Comment by pulkithanda** [comment]
Hmm I'm facing an error while cloning cant see them

**Review by gamer-1478 — CHANGES_REQUESTED** [review]
image
Hi, This looks like its not working as intended, and does not scale. It also does not work with the phone sidenav, as seen in the screen shot below. 
image
It also dislodges the current navbar button position to the middle of the screen.
image

**Comment by gamer-1478** [comment]
I would also suggest you should place all the css in the main.css and not use styles tag as to be inline with the current project structure.

**Comment by pulkithanda** [comment]
@JanviRaina Do you want to work further or do i mark it as hacktoberfest-accepted if you aren't able to ?

**Comment by JanviRaina** [comment]
> @JanviRaina Do you want to work further or do i mark it as hacktoberfest-accepted if you aren't able to ?

You can mark it as hacktoberfest-accepted.

**Comment by pulkithanda** [comment]
Ok @JanviRaina Sure great work. Thank you for contributing ^_^.

**Comment by pulkithanda** [comment]
Do tell me if you have any problems, it should show on your hf profile in sometime.

**Pull request closed without merging**
