### PR TITLE
Contact form

### PR DESCRIPTION
**Pull request by Harsh-Singh-Rajput**

### CODE REVIEW

**Comment by akgupta0777** [comment]
Fixes #48

**Review by akgupta0777 — CHANGES_REQUESTED** [review]
Where is the route.py file please add that too and push

**Review by akgupta0777 — APPROVED** [review]
Seems good only task left is to link backend.

**Comment by Harsh-Singh-Rajput** [comment]
> Seems good only task left is to link backend.

Added google sheet for storing data learning flask in for future update

**Comment by Harsh-Singh-Rajput** [comment]
> Ohh you added the google sheet in the contact form as script tag.
> 
> Nice work ! Hope you learned something new. 😄
> 
> Everything is working fine I am approving this

yes learnt something new😊

**Comment by pulkithanda** [comment]
@akgupta0777 Thanks for reviewing mate. @Harsh-Singh-Rajput Thank you for contributing ^_^. 
(btw if it helped you pls do follow me and star the repo, helps me a lot thanks guys)

**Comment by akgupta0777** [comment]
@pulkithanda Lets follow each other 😅

**Pull request merged**
